### ISSUE TITLE
能否支持网易云音乐电台节目播放？

### ISSUE THREAD

**Issue by Jackeriss** [YUX-IO/163music-APlayer-you-get-docker#1]
云音乐有许多歌曲是以电台节目的形式存在的，官方是可以生成外链播放器的，这个应该也可以支持吧？

**Comment by Jackeriss** [comment]
貌似网易没有公开电台节目的API...

**Comment by YUX** [comment]
@Jackeriss 我去研究一下 之前没用过电台

**Comment by Jackeriss** [comment]
您好，最近you-get已经支持云音乐电台节目的下载，请问现在能否支持电台节目播放呢？

**Comment by YUX** [comment]
@Jackeriss 好的 我这两天抓紧看一下 最快明天加上

**Comment by YUX** [comment]
@Jackeriss 已经支持了 你去试一下 http://music.daoapp.io/

**Comment by Jackeriss** [comment]
之前调用 iframe 的方法不能用了吗？现在 https://music.daoapp.io/iframe/song?id=27808044&qssl=1&qlrc=1&narrow=0 这个链接显示404。

**Comment by YUX** [comment]
@Jackeriss 不好意思现在的 beta5还没有写完 今天会写完

**Comment by YUX** [comment]
@Jackeriss 写完会支持iframe,以后会先写完再上线,不会像这次这样了^_^

**Comment by Jackeriss** [comment]
嗯，支持你！

**Comment by YUX** [comment]
@Jackeriss 已修复 iframe. 但请参考文档修改参数,例如 https://music.daoapp.io/iframe/song?id=27808044&qssl=1&qlrc=1&narrow=0 要修改为 https://music.daoapp.io/iframe?song=27808044&qssl=1&qlrc=1&narrow=false
