### ISSUE TITLE
README.md中有一处错误

### ISSUE THREAD

**Issue by Jackeriss** [YUX-IO/163music-APlayer-you-get-docker#2]
beta5更新的iframe的参数说明中autoplay的可选值应为[0|1]，文档中写成了[true|false]

**Comment by Jackeriss** [comment]
好像两种都可以是吧，那为啥不统一成 [0|1] 呢？这样更清晰一点。

**Comment by YUX** [comment]
@Jackeriss 统一将文档改成 [0|1]了, thanks
