### ISSUE TITLE
增加不重複播放開關

### ISSUE THREAD

**Issue by hoginwang** [YUX-IO/163music-APlayer-you-get-docker#6]
增加一個歌曲僅播放一次的開關，尤其在只會播放一首歌曲的時候，播完結束之後又自動重播好像不太符合日常習慣。

**Comment by DIYgod** [comment]
这个么？

![](http://ww1.sinaimg.cn/large/72f96cbagw1f8bp5foeukj20ta08gmy3.jpg)

**Comment by hoginwang** [comment]
用iframe的話有url參數可供配置麼？
